# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 다들 졸리죠?
email: trust1303@naver.com
description: 삶은 계란

baseurl: "" #e.g. /safarnama, /blog. Dont forget the '/'.
url: "http://trust1303.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: trust1303
 
   
# Build settings
markdown: kramdown
