# Setup
title:        trust1303.github.io
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       trust1303
  url:        trust1303.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
